#ifndef ALLEGROCOLORS_H
#define ALLEGROCOLORS_H

#include <allegro5/allegro.h> //for ALLEGRO_COLOR

struct Colors{
    ALLEGRO_COLOR BLACK;
    ALLEGRO_COLOR WHITE;
    ALLEGRO_COLOR RED;
    ALLEGRO_COLOR GREEN;
    ALLEGRO_COLOR BLUE;
    ALLEGRO_COLOR PURPLE;

    ALLEGRO_COLOR BACKGROUND;
    ALLEGRO_COLOR BOARD_COLOR;
    ALLEGRO_COLOR SMALL_BOARD_COLOR;
    ALLEGRO_COLOR CURSOR;
    ALLEGRO_COLOR CURSOR_P1;
    ALLEGRO_COLOR CURSOR_P2;
    ALLEGRO_COLOR CURSOR_ERROR;

    void initialize();
};

#endif // ALLEGROCOLORS_H
